version: 2

jobs:
  compile:
    docker:
      - image: ubuntu:20.04
        working_directory: ~/libtest
        environment:
          CI_FORCE_TEST: 1
    steps:
      - run:
          command: |
            apt update -qq
            DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get -y install tzdata
            apt install -y --no-install-recommends software-properties-common wget gpg-agent shellcheck
            apt install -y --no-install-recommends git make pkg-config libtool autoconf intltool
            apt install -y --no-install-recommends gcc-10
      - checkout
      - run:
          command: |
            export CFLAGS=-Werror
            echo
            echo "########## gcc-10 ##########"
            ./autogen.sh
            ./configure
            CC=gcc-10 make
            make clean

  package-and-publish-release:
    machine: true
    working_directory: ~/libtest
    steps:
      - checkout
      - run:
          name: "package with packagecore"
          command: |
            # Clean up
            rm -rf ./dist/*
            # Pack source
            git archive -o ../${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}.tar.gz --format tar.gz --prefix=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG#v}/ ${CIRCLE_TAG}
            # Use latest installed python3 from pyenv
            export PYENV_VERSION="$(pyenv versions | grep -Po '\b3\.\d+\.\d+' | tail -1)"
            pip install packagecore
            packagecore -c misc/packagecore/packagecore.yaml -o ./dist/ ${CIRCLE_TAG#v} ${CIRCLE_BUILD_NUM}
            # Move source pack to dist
            mv ../${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}.tar.gz dist/
      - run:
          name: "publish to GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_API_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./dist/
      - run:
          name: "publish to Bintray"
          command: |
            BINTRAY_USER=${CI_BINTRAY_USER} BINTRAY_PASS=${CI_BINTRAY_API_KEY} BINTRAY_COMPONENT=release BINTRAY_ORG=aeco python ./misc/bintray/bintray.py publish ./dist
workflows:
  version: 2

  test:
    jobs:
      - compile

  publish-github-release:
    jobs:
      - package-and-publish-release:
          context: CI_BUILD
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

# workflows:
#  version: 2
#  build:
#    jobs:
#      - lint
#      - build:
#          filters:
#            branches:
#              only:
#                - master
#      - publish:
#          requires:
#            - lint
#            - build
